blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/samwillis/tetra/discussions/new
    about: Request a feature to be added to the platform
  - name: Ask a Question
    url: https://github.com/samwillis/tetra/discussions/new
    about: Ask questions and discuss with other community members